---
# Tasks for home directory configuration

- name: Configure home directory permissions
  ansible.builtin.file:
    path: "{{ item.home | default('/home/' + item.username) }}"
    mode: "{{ item.home_mode | default('0750') }}"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.group | default(item.username) }}"
    recurse: true
  loop: "{{ users }}"
  when: 
    - item.state | default('present') == 'present'
    - item.username is defined
  tags: ['user', 'home']

- name: Create public_html directory
  ansible.builtin.file:
    path: "{{ item.home | default('/home/' + item.username) }}/public_html"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.group | default(item.username) }}"
    mode: "{{ item.public_html_mode | default('0755') }}"
  loop: "{{ users }}"
  when: 
    - item.state | default('present') == 'present'
    - item.username is defined
    - item.public_html | default(false) | bool
  tags: ['user', 'home', 'public_html']
