---
# Tasks for sudo configuration

- name: Configure sudo access
  community.general.sudoers:
    name: "{{ user_name }}"
    user: "{{ user_name }}"
    commands: "{{ user_sudo_commands }}"
  become: true
  when: 
    - user_name | length > 0
    - user_sudo_enabled | bool
    - user_sudo_commands | length > 0
  tags: ['user', 'sudo']
